name = "hono-firebase-auth"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# ضع معلومات Firebase هنا
FIREBASE_PROJECT_ID = "your-project-id"
FIREBASE_CLIENT_EMAIL = "your-client-email"
FIREBASE_PRIVATE_KEY = "your-private-key"